### ISSUE TITLE
Wrong builds in yaml file.

### ISSUE THREAD

**Issue by JLans** [Savoie-Research-Group/yarp#9]
Some of the package bulilds in the yaml file, such as, libblas==3.9.0=16_osx64_openblas and boost==1.74.0=py38hb0f0857_5, are for osx not linux.

**Comment by Zhaoli2042** [comment]
Hi,

Please take a look at the GitHub workflow file that compiles YARP during the workflow, for ubuntu-Linux.
https://github.com/Savoie-Research-Group/yarp/blob/master/.github/workflows/python-test.yml

We will update the installation file in readme.md shortly. 

Thanks, 
Zhao

**Comment by Zhaoli2042** [comment]
We have updated our installation instructions on Linux ([README.md](https://github.com/Savoie-Research-Group/yarp/blob/master/README.md)). Please follow the instructions and see if they work on your system. 
Please let us know if you have any questions!

**Comment by JLans** [comment]
It worked. Thank you!
